name: Release

on:
    push:
        branches:
            - main

jobs:
    semantic-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: lts/*
                  cache: npm
            - run: npm ci
            - run: npm audit signatures
            - run: npx semantic-release
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
